# Generated by Django 4.2.1 on 2023-07-07 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DarkJokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_joke', models.TextField(help_text='Enter a dark joke')),
                ('like_count', models.BigIntegerField(default='0')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like_dark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.TextField(help_text='Enter a joke')),
                ('like_count', models.BigIntegerField(default='0')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like_joke', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='memes/download.jpg', upload_to='media/memes')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('likes', models.ManyToManyField(related_name='story_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='upload a short', max_length=50)),
                ('video', models.FileField(default='shorts/download.mp4', upload_to='media/shorts')),
                ('source', models.CharField(default='#', max_length=255)),
                ('like_count', models.BigIntegerField(default='0')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like_short', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='upload a meme', max_length=50)),
                ('image', models.ImageField(default='memes/download.jpg', upload_to='media/memes')),
                ('like_count', models.BigIntegerField(default='0')),
                ('category', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_joke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.darkjokes')),
                ('joke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jokes')),
                ('meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.memes')),
                ('short', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shorts')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stories')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
