# Generated by Django 4.2.4 on 2024-01-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shorts_video_alter_stories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
