# Generated by Django 4.0.6 on 2022-08-22 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_stories_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='author',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(default='memes/download.jpg', upload_to='uploads/memes'),
        ),
        migrations.AddField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
