# Generated by Django 4.2.4 on 2024-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_memes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='source',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
