# Generated by Django 4.0.6 on 2022-08-22 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_stories_author_remove_stories_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
