# Generated by Django 4.2.4 on 2024-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shorts_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='thumbnail',
            field=models.ImageField(blank=True, default='shorts/thumbnails/download.jpg', upload_to='shorts/thumbnails'),
        ),
    ]
