# Generated by Django 4.0.6 on 2022-08-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stories_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='likes',
        ),
    ]
