# Generated by Django 4.0.6 on 2022-09-11 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_stories_likes_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='likes',
            field=models.ManyToManyField(related_name='story_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
