# Generated by Django 4.0.6 on 2022-09-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='user_id',
            new_name='user',
        ),
    ]
