# Generated by Django 4.0.6 on 2022-10-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_story_id_likepost_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(default='memes/download.jpg', upload_to='https://drive.google.com/drive/folders/1_gO2nfe7th0Xv9waUdtnIK27nC8Livmy?usp=sharing'),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='video',
            field=models.CharField(default='shorts/download.mp4', max_length=1000),
        ),
    ]
