# Generated by Django 4.0.6 on 2022-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_memes_image_alter_shorts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
