# Generated by Django 4.0.6 on 2022-11-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_stripecustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(default='memes/download.jpg', upload_to='uploads/memes'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
