# Generated by Django 4.0.6 on 2023-01-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
