# Generated by Django 4.0.6 on 2023-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_memes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='source',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='video',
            field=models.FileField(default='shorts/download.mp4', upload_to='uploads/shorts'),
        ),
    ]
