# Generated by Django 4.0.6 on 2023-02-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_likepost_story_alter_memes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='meme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.memes'),
        ),
    ]
