# Generated by Django 4.0.6 on 2023-02-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_likepost_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='dark_joke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.darkjokes'),
        ),
        migrations.AddField(
            model_name='likepost',
            name='joke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jokes'),
        ),
        migrations.AddField(
            model_name='likepost',
            name='short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shorts'),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stories'),
        ),
    ]
