# Generated by Django 4.0.6 on 2023-02-20 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_likepost_dark_joke_likepost_joke_likepost_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='likes',
            field=models.ManyToManyField(related_name='meme_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
