# Generated by Django 4.0.6 on 2023-02-22 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0024_memes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkjokes',
            name='likes',
            field=models.ManyToManyField(related_name='dark_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jokes',
            name='likes',
            field=models.ManyToManyField(related_name='joke_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shorts',
            name='likes',
            field=models.ManyToManyField(related_name='short_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
