# Generated by Django 4.0.6 on 2023-03-17 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_memes_like_count_alter_memes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_short', to=settings.AUTH_USER_MODEL),
        ),
    ]
