# Generated by Django 4.0.6 on 2023-03-17 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_shorts_like_count_alter_shorts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkjokes',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='jokes',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='darkjokes',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_dark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jokes',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_joke', to=settings.AUTH_USER_MODEL),
        ),
    ]
